# Generated by Django 2.2.10 on 2020-02-13 18:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('y_coordinate', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('points_quantity', models.IntegerField(default=1)),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.OperationType')),
            ],
        ),
    ]
