# Generated by Django 2.2.10 on 2020-02-14 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='x_coordinate',
            new_name='point_input',
        ),
        migrations.RemoveField(
            model_name='point',
            name='y_coordinate',
        ),
    ]
