# Generated by Django 2.2.10 on 2020-02-14 11:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20200214_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'points',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
