# Generated by Django 2.2.10 on 2020-02-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_auto_20200214_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='points',
            options={'managed': False, 'verbose_name_plural': 'Points'},
        ),
    ]
