# Generated by Django 2.2.10 on 2020-02-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_actor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='OperationType',
        ),
    ]
